name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Before build
      env:
        CC_TEST_REPORTER_ID: e84e5886d1afa01c8c566738b62f6e4d5efc883df4f63668ce0d28605e1fb9fd
      run: wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -O cc-test-reporter && chmod +x cc-test-reporter && ./cc-test-reporter before-build
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml -Dmaven.test.failure.ignore=true
    - name: Generate coverage
      run: mvn jacoco:report --file pom.xml
    - name: Publish report
      env:
        CC_TEST_REPORTER_ID: 84e73d26eaa0ab4463a8990afb35e1902db4e8e93e10257c9c42f375da533b9c
        JACOCO_SOURCE_PATH: src/main/kotlin
      run: export GIT_BRANCH=`echo $GITHUB_REF | cut -d '/' -f '3-'` && export GIT_COMMIT_SHA=$GITHUB_SHA && ./cc-test-reporter format-coverage target/site/jacoco/jacoco.xml --input-type jacoco -d && ./cc-test-reporter upload-coverage -d
    - name: Check test failures
      run: failures=`grep '<<< FAILURE!' target/surefire-reports -r | wc -l` && if [[ failures -gt 0 ]]; then exit 1; else exit 0; fi
